version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres:15.11
    restart: always
    shm_size: '2gb'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"

volumes:
  postgres-data: