version: '3.9'


services:
  app:
    container_name: pharma-api
    build:
      context: docker
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_PORT: ${PG_PORT}
    ports:
      - "${HTTP_PORT}:8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15.11
    restart: always
    shm_size: '2gb'  # Optional, remove if not needed
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"  # More secure than md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - "${PG_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
