ALTER TABLE imports ADD COLUMN IF NOT EXISTS "name" VARCHAR(255);
ALTER TABLE imports ADD COLUMN IF NOT EXISTS "entry_type" INT DEFAULT 1; -- 1 - IMPORT | 2 - INVENTORY | 3 - WRITE-OFF
ALTER TABLE imports ADD COLUMN IF NOT EXISTS "inventory_type" VARCHAR(55); --> FULL || PARTIAL