ALTER TABLE stores ADD COLUMN IF NOT EXISTS "is_tax" BOOLEAN;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS "employee_count" INT DEFAULT 0;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS "cash_box_count" INT DEFAULT 0;