CREATE TABLE IF NOT EXISTS "products" (
  "id" uuid PRIMARY KEY,
  "store_id" uuid,
  "category_id" uuid,
  "brand_id" uuid,
  "supplier_id" uuid,
  "unit_id" uuid,
  "product_type" product_type_enum,
  "product_variability" product_variability,
  "name" VARCHAR(255),
  "sku" VARCHAR(255) UNIQUE,
  "barcode" VARCHAR(255),
  "main_photo" VARCHAR,
  "photos" VARCHAR[],
  "supply_price" NUMERIC(10, 2),
  "markup" INT,
  "retail_price" NUMERIC(10, 2),
  "quantity" INT,
  "sum" NUMERIC(10, 2),
  "description" TEXT,
  "status" product_status,
  "manufacturer" VARCHAR,
  "expire_date" DATE,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);