CREATE TABLE IF NOT EXISTS "products" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "brand_id" UUID REFERENCES "brands"("id"),
  "unit_type_id" UUID REFERENCES "unit_types"("id"),
  "name" VARCHAR(255),
  "barcode" VARCHAR(255),
  "photos" VARCHAR[],
  "supply_price" NUMERIC(10, 2),
  "vat" INT,
  "vat_price" NUMERIC(10, 2),
  "vat_sum" NUMERIC(10, 2),
  "markup" INT DEFAULT 0,
  "retail_price" NUMERIC(10, 2),
  "quantity" INT,
  "unit_per_pack" INTEGER DEFAULT 0, -- 1 pochkada necha dona borligini saqlaydi
  "sum" NUMERIC(10, 2),
  "description" TEXT,
  "status" product_status,
  "bonus_percent" INT DEFAULT 0,
  "bonus_amount" NUMERIC(10, 2) DEFAULT 0,
  "manufacturer" VARCHAR,
  "material_code" INT UNIQUE,
  "expire_date" DATE,
  "product_series_number" VARCHAR,
  "created_by" uuid,
  "updated_by" uuid,
  "deleted_by" uuid,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);