CREATE TABLE IF NOT EXISTS "products" (
  "id" uuid PRIMARY KEY,
  "store_id" uuid,
  "category_id" uuid,
  "brand_id" uuid,
  "supplier_id" uuid,
  "unit_id" uuid,
  "product_type" product_type_enum,
  "product_variability" product_variability,
  "name" varchar(255),
  "sku" varchar(255) UNIQUE,
  "barcode" varchar(255),
  "unit" varchar(255),
  "main_photo" varchar,
  "photos" varchar[],
  "supply_price" int,
  "markup" int,
  "retail_price" int,
  "quantity" int,
  "desc" text,
  "status" product_status,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);