CREATE TABLE IF NOT EXISTS "products" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "store_id" UUID,
  "brand_id" UUID,
  "supplier_id" UUID,
  "unit_id" UUID,
  "receipt_id" UUID REFERENCES "product_receipts"("id"),
  "store_code" INT REFERENCES "stores"("store_code"),
  "product_type" product_type_enum,
  "product_variability" product_variability,
  "name" VARCHAR(255),
  "barcode" VARCHAR(255),
  "main_photo" VARCHAR,
  "photos" VARCHAR[],
  "supply_price" NUMERIC(10, 2),
  "vat" INT,
  "vat_price" NUMERIC(10, 2),
  "vat_sum" NUMERIC(10, 2),
  "markup" INT,
  "retail_price" NUMERIC(10, 2),
  "quantity" INT,
  "sum" NUMERIC(10, 2),
  "description" TEXT,
  "status" product_status,
  "bonus_percent" INT,
  "bonus_amount" NUMERIC(10, 2),
  "manufacturer" VARCHAR,
  "material_code" INT,
  "expire_date" DATE,
  "product_series_number" VARCHAR,
  "created_by" uuid,
  "updated_by" uuid,
  "deleted_by" uuid,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);