ALTER TABLE "import_details"
    ADD COLUMN IF NOT EXISTS "country" VARCHAR(255),
    ADD COLUMN IF NOT EXISTS "is_return" BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "requires_prescription" BOOLEAN NOT NULL DEFAULT FALSE;
