ALTER TABLE IF EXISTS products
    ADD COLUMN IF NOT EXISTS last_updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE IF EXISTS store_products
    ADD COLUMN IF NOT EXISTS last_updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
