ALTER TABLE IF EXISTS sales
    DROP COLUMN IF EXISTS cash,
    DROP COLUMN IF EXISTS humo,
    DROP COLUMN IF EXISTS uzcard,
    DROP COLUMN IF EXISTS payme,
    DROP COLUMN IF EXISTS alif,
    DROP COLUMN IF EXISTS is_paid,
    DROP COLUMN IF EXISTS check_url;
