-- Add payment method columns
ALTER TABLE IF EXISTS sales
    ADD COLUMN IF NOT EXISTS cash   NUMERIC(10, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS humo   NUMERIC(10, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS uzcard NUMERIC(10, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS payme  NUMERIC(10, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS alif   NUMERIC(10, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS return_amount NUMERIC(10, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS is_paid BOOLEAN       DEFAULT false,
    ADD COLUMN IF NOT EXISTS check_url VARCHAR(255);
