DROP EXTENSION IF EXISTS postgis;

ALTER TABLE 
    "stores"
        DROP COLUMN IF EXISTS "contact" VARCHAR(20) NULL,
        DROP COLUMN IF EXISTS "inn" VARCHAR(55) NULL,
        DROP COLUMN IF EXISTS "landmark" VARCHAR(255) NULL,
        DROP COLUMN IF EXISTS "coordinates" GEOGRAPHY(POINT, 4326) NULL;