ALTER TABLE "employees" ADD COLUMN IF NOT EXISTS "avg_monthly_hours" NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "employees" ADD COLUMN IF NOT EXISTS "kpi_percent" NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "employees" ADD COLUMN IF NOT EXISTS "experience_years" NUMERIC(5,1) NOT NULL DEFAULT 0;
