ALTER TABLE transfers ADD COLUMN IF NOT EXISTS "driver_ofis"   VARCHAR(255) DEFAULT NULL;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS "driver_store_a" VARCHAR(255) DEFAULT NULL;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS "driver_store_b" VARCHAR(255) DEFAULT NULL;

