basePath: /v1
definitions:
  domain.Employee:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      language:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone:
        type: string
      role_id:
        type: string
      updated_at:
        type: string
    type: object
  v1.RequestBody-domain_Employee:
    properties:
      data:
        $ref: '#/definitions/domain.Employee'
    type: object
  v1.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      ok:
        type: boolean
    type: object
info:
  contact: {}
  description: This is a sample server caller server.
  termsOfService: http://swagger.io/terms/
  title: Pharma API docs
  version: "1.0"
paths:
  /employee:
    delete:
      consumes:
      - application/json
      description: Delete an employee by id
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Employee id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - BearerAuth: []
      summary: Delete employee
      tags:
      - employees
    get:
      consumes:
      - application/json
      description: Get an employee by id
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Employee id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - BearerAuth: []
      summary: Get employee
      tags:
      - employees
    post:
      consumes:
      - application/json
      description: Create a new employee in the system
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Employee data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.RequestBody-domain_Employee'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - BearerAuth: []
      summary: Create employee
      tags:
      - employees
    put:
      consumes:
      - application/json
      description: Update an employee
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Employee data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.RequestBody-domain_Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - BearerAuth: []
      summary: Update employee
      tags:
      - employees
  /employees:
    get:
      consumes:
      - application/json
      description: List all employees
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/v1.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - BearerAuth: []
      summary: List employees
      tags:
      - employees
securityDefinitions:
  BasicAuth:
    type: basic
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
